### ISSUE TITLE
GitHubActionsにおける、db接続エラーについて

### ISSUE THREAD

**Issue by wassupdee** [wassupdee/RUNTEQ_portfolio#167]
### 実装したいもの・解決したいもの
GitHubActionsにおいて、rspecを実行するための環境構築を実行したいです。
DBを作成する際、MySQLコンテナに接続できず、エラーが起きてしまいます。
このエラーを解消したいです。

### エラー内容
```
Run cp config/database.yml.ci config/database.yml
  cp config/database.yml.ci config/database.yml
  bundle exec rails db:create RAILS_ENV=test
  bundle exec rails db:migrate RAILS_ENV=test
  shell: /usr/bin/bash -e {0}
  env:
    OPENAI_ACCESS_TOKEN: ***
    LINE_CHANNEL_ID_LOGIN: ***
    LINE_CHANNEL_SECRET_LOGIN: ***
There is an issue connecting with your hostname: db.

Please check your database configuration and ensure there is a valid connection to your database.
Couldn't create 'myapp_test' database. Please check your configuration.
bin/rails aborted!
ActiveRecord::DatabaseConnectionError: There is an issue connecting with your hostname: db. (ActiveRecord::DatabaseConnectionError)
```

#### エラーの意味
- "db"というホストに接続できず、DBが作成できない

#### 推測される原因
- dbというコンテナがうまく立ち上がっていない　→　ログを見て、問題なく立ち上がっていることを確認
```
Create local container network
  /usr/bin/docker network create --label 1c9149 github_network_269a18c625594a1da1b2d46b0bc[12](https://github.com/wassupdee/RUNTEQ_portfolio/actions/runs/10438323689/job/28905499167?pr=166#step:2:14)2ff
  a22e662c35bb2d013c9a6696fd8cc425103d01d7b8e2f5df81a77f969dc71fb2
Starting db service container
  /usr/bin/docker pull mysql:8.0
  8.0: Pulling from library/mysql
  d9a40b27c30f: Pulling fs layer
  7d8ccc83ce1d: Pulling fs layer
  f98ae2ef29c4: Pulling fs layer
  2e1aa9898aa1: Pulling fs layer
  d0229fb4f83e: Pulling fs layer
  bdfea4c359d4: Pulling fs layer
  d6fe59aa1e5c: Pulling fs layer
  7336dce1c47f: Pulling fs layer
  1c71c9d185d1: Pulling fs layer
  e63d4802c63b: Pulling fs layer
  383f329967ab: Pulling fs layer
  d6fe59aa1e5c: Waiting
  7336dce1c47f: Waiting
  1c71c9d185d1: Waiting
  e63d4802c63b: Waiting
  383f329967ab: Waiting
  d0229fb4f83e: Waiting
  bdfea4c359d4: Waiting
  2e1aa9898aa1: Waiting
  7d8ccc83ce1d: Download complete
  f98ae2ef29c4: Verifying Checksum
  f98ae2ef29c4: Download complete
  d0229fb4f83e: Verifying Checksum
  d0229fb4f83e: Download complete
  2e1aa9898aa1: Verifying Checksum
  2e1aa9898aa1: Download complete
  bdfea4c359d4: Verifying Checksum
  bdfea4c359d4: Download complete
  7336dce1c47f: Verifying Checksum
  7336dce1c47f: Download complete
  d9a40b27c30f: Verifying Checksum
  d9a40b27c30f: Download complete
  d6fe59aa1e5c: Verifying Checksum
  d6fe59aa1e5c: Download complete
  e63d4802c63b: Verifying Checksum
  e63d4802c63b: Download complete
  383f329967ab: Verifying Checksum
  383f329967ab: Download complete
  1c71c9d185d1: Verifying Checksum
  1c71c9d185d1: Download complete
  d9a40b27c30f: Pull complete
  7d8ccc83ce1d: Pull complete
  f98ae2ef29c4: Pull complete
  2e1aa9898aa1: Pull complete
  d0229fb4f83e: Pull complete
  bdfea4c359d4: Pull complete
  d6fe59aa1e5c: Pull complete
  7336dce1c47f: Pull complete
  1c71c9d185d1: Pull complete
  e63d4802c63b: Pull complete
  383f329967ab: Pull complete
  Digest: sha256:25d44c5eeef80daf6a6d8c9c2bc2e77e72307e8b7fddf96a8a7d4bda777f0a17
  Status: Downloaded newer image for mysql:8.0
  docker.io/library/mysql:8.0
  /usr/bin/docker create --name 8197609cec0a4ded909732d16b8b8e38_mysql80_6a54cf --label 1c9[14](https://github.com/wassupdee/RUNTEQ_portfolio/actions/runs/10438323689/job/28905499167?pr=166#step:2:17)9 --network github_network_269a18c625594a1da1b2d46b0bc122ff --network-alias db -p 3307:3306 --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -ppassword" --health-interval=10s --health-timeout=10s --health-retries=3 --health-start-period=30s -e "MYSQL_ROOT_PASSWORD=password" -e "TZ=Asia/Tokyo" -e GITHUB_ACTIONS=true -e CI=true mysql:8.0
  4926[20](https://github.com/wassupdee/RUNTEQ_portfolio/actions/runs/10438323689/job/28905499167?pr=166#step:2:23)928a72729f5f3ee2633b397cf1ddea535a073ff7981e65710d0a7b5045
  /usr/bin/docker start 492620928a72729f5f3ee2633b397cf1ddea535a073ff7981e65710d0a7b5045
  492620928a72729f5f3ee2633b397cf1ddea535a073ff7981e65710d0a7b5045
  /usr/bin/docker ps --all --filter id=49[26](https://github.com/wassupdee/RUNTEQ_portfolio/actions/runs/10438323689/job/28905499167?pr=166#step:2:29)20928a72729f5f3ee2633b397cf1ddea535a073ff7981e65710d0a7b5045 --filter status=running --no-trunc --format "{{.ID}} {{.Status}}"
  492620928a7[27](https://github.com/wassupdee/RUNTEQ_portfolio/actions/runs/10438323689/job/28905499167?pr=166#step:2:30)29f5f3ee2633b397cf1ddea535a073ff7981e65710d0a7b5045 Up Less than a second (health: starting)
  /usr/bin/docker port 4926209[28](https://github.com/wassupdee/RUNTEQ_portfolio/actions/runs/10438323689/job/28905499167?pr=166#step:2:31)a72729f5f3ee2633b397cf1ddea535a073ff7981e65710d0a7b5045
  3306/tcp -> 0.0.0.0:3307
  3306/tcp -> [::]:3307
Waiting for all services to be ready
  /usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" 492620928a727[29](https://github.com/wassupdee/RUNTEQ_portfolio/actions/runs/10438323689/job/28905499167?pr=166#step:2:32)f5f3ee2633b397cf1ddea535a073ff7981e65710d0a7b5045
  starting
  db service is starting, waiting 2 seconds before checking again.
  /usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" 492620928a72729f5f3ee26[33](https://github.com/wassupdee/RUNTEQ_portfolio/actions/runs/10438323689/job/28905499167?pr=166#step:2:36)b397cf1ddea535a073ff7981e65710d0a7b5045
  starting
  db service is starting, waiting 4 seconds before checking again.
  /usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" 492620928a72729f5f3ee2633b397cf1ddea5[35](https://github.com/wassupdee/RUNTEQ_portfolio/actions/runs/10438323689/job/28905499167?pr=166#step:2:38)a073ff7981e65710d0a7b5045
  starting
  db service is starting, waiting 7 seconds before checking again.
  /usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" 492620928a72729f5f3ee2633b[39](https://github.com/wassupdee/RUNTEQ_portfolio/actions/runs/10438323689/job/28905499167?pr=166#step:2:42)7cf1ddea535a073ff7981e65710d0a7b5045
  healthy
  db service is healthy.
```
### .github/workflows/rubyonrails.yml
```
# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "auto test and deploy"
on: push
jobs:
  rspec:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    services:
      db:
        image: mysql:8.0
        ports:
          - 3307:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          TZ: Asia/Tokyo
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -ppassword"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=3
          --health-start-period=30s
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3
          bundler-cache: true

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Bundler and gem install
        run: |
          gem install bundler
          bundle install

      - name: Set environment variables
        run: |
          echo "OPENAI_ACCESS_TOKEN=${{ secrets.OPENAI_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "LINE_CHANNEL_ID_LOGIN=${{ secrets.LINE_CHANNEL_ID_LOGIN }}" >> $GITHUB_ENV
          echo "LINE_CHANNEL_SECRET_LOGIN=${{ secrets.LINE_CHANNEL_SECRET_LOGIN }}" >> $GITHUB_ENV

      - name: Precompile assets
        run: bundle exec rails assets:precompile RAILS_ENV=test

      - name: Database create and migrate
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Run rspec
        run: bundle exec rspec



  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3
          bundler-cache: true

      - name: Bundler and gem install
        run: |
          gem install bundler
          bundle install

      - name: Run rubocop
        run: bundle exec rubocop
```

### config/database.yml.ci
```
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

test:
  <<: *default
  database: myapp_test
```

### 実装する際に参考にした資料
- https://qiita.com/JZ8xNeXY/items/fef7efb5eb9495b62faf
- https://zenn.dev/ryouzi/articles/cd6857c08e60e7
### エラーを解決するために調べた資料
良い資料が見つからず、ChatGPTに確認しました。
コンテナのログから、1, 3, 4, 5は確認済みです。
2番だけは確認方法が分かっておりません。

以下、ChatGPTの回答です。

---

このエラーメッセージから、MySQLサーバーが正しく起動していないか、あるいはRailsがMySQLサーバーに接続できていない可能性が考えられます。いくつかの原因が考えられるので、順番に確認してみましょう。

### 1. MySQLサーバーの起動確認

MySQLサーバーがGitHub Actionsの環境で正しく起動していない可能性があります。`services`セクションでMySQLを指定していますが、サービスの起動が完了する前に接続を試みている可能性があります。

#### 確認方法:
- MySQLが正しく起動しているか確認するために、MySQLサーバーが起動してからRailsのコマンドが実行されるように、以下のように**スリープ**を追加して、サービスが完全に起動するのを待ちます。

```yaml
- name: Wait for MySQL to be ready
  run: sleep 10
```

### 2. MySQLの`host`設定が正しいか

エラーメッセージに`Unknown MySQL server host 'db'`とありますが、`host: db`が正しく設定されていない可能性もあります。`host: db`が正しいサービス名であることを確認してください。

#### 対策:
- `database.yml.ci`の`host`を再度確認し、`db`が正しいサービス名であることを確認します。

### 3. MySQLコンテナの起動確認

MySQLコンテナ自体が正しく起動していない可能性があります。この場合、GitHub Actionsのサービスログを確認して、MySQLサービスが正しく起動しているかどうかを確認します。

#### 対策:
- MySQLの起動時にエラーがないか、ログを確認します。エラーがある場合は、それを修正する必要があります。

### 4. Dockerのヘルスチェックを追加する

MySQLが完全に起動する前にRailsがデータベースに接続しようとしているためにエラーが発生している可能性もあります。その場合、Dockerのヘルスチェックを追加することで、MySQLが完全に起動した後に次のステップが実行されるように設定できます。

#### 例:
`docker-compose.yml`での`healthcheck`の設定例を参考に、MySQLサービスにヘルスチェックを追加してみてください。

```yaml
services:
  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uroot -ppassword
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
```

### 5. MySQLコンテナが作成されているか確認

MySQLコンテナが実際に作成されていない場合も考えられます。これは、`docker-compose`やGitHub Actionsの設定が正しくない場合に発生することがあります。

#### 対策:
- サービスセクションで定義されたMySQLコンテナが正しく作成されているか確認します。`docker-compose ps`のようなコマンドを使って、コンテナの状態を確認できます。

### まとめ

上記のチェックポイントを確認しながら、エラーの原因を絞り込んでください。特に、MySQLが正しく起動しているか、Railsが正しいホストとポートでMySQLに接続しようとしているかを確認することが重要です。
